activity_log_in.xml was missing the android:id="@+id/main"
  /Users/amielpeled/AndroidStudioProjects/EscapeRooms/app/src/main/res/layout/create_room.xml:13:

  Error: This view is not constrained. It only has designtime positions, so it will jump to (0,0) at runtime unless you add the constraints [MissingConstraints]
      <ImageView
       ~~~~~~~~~